# CMake generated Testfile for 
# Source directory: R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx
# Build directory: D:/dev/glm/test/gtx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_associated_min_max "D:/dev/glm/test/gtx/Debug/test-gtx_associated_min_max.exe")
  set_tests_properties(test-gtx_associated_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_associated_min_max "D:/dev/glm/test/gtx/Release/test-gtx_associated_min_max.exe")
  set_tests_properties(test-gtx_associated_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_associated_min_max "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_associated_min_max.exe")
  set_tests_properties(test-gtx_associated_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_associated_min_max "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_associated_min_max.exe")
  set_tests_properties(test-gtx_associated_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_associated_min_max NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_bit "D:/dev/glm/test/gtx/Debug/test-gtx_bit.exe")
  set_tests_properties(test-gtx_bit PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_bit "D:/dev/glm/test/gtx/Release/test-gtx_bit.exe")
  set_tests_properties(test-gtx_bit PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_bit "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_bit.exe")
  set_tests_properties(test-gtx_bit PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_bit "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_bit.exe")
  set_tests_properties(test-gtx_bit PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_bit NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_closest_point "D:/dev/glm/test/gtx/Debug/test-gtx_closest_point.exe")
  set_tests_properties(test-gtx_closest_point PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_closest_point "D:/dev/glm/test/gtx/Release/test-gtx_closest_point.exe")
  set_tests_properties(test-gtx_closest_point PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_closest_point "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_closest_point.exe")
  set_tests_properties(test-gtx_closest_point PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_closest_point "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_closest_point.exe")
  set_tests_properties(test-gtx_closest_point PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_closest_point NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_color_space_YCoCg "D:/dev/glm/test/gtx/Debug/test-gtx_color_space_YCoCg.exe")
  set_tests_properties(test-gtx_color_space_YCoCg PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_color_space_YCoCg "D:/dev/glm/test/gtx/Release/test-gtx_color_space_YCoCg.exe")
  set_tests_properties(test-gtx_color_space_YCoCg PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_color_space_YCoCg "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_color_space_YCoCg.exe")
  set_tests_properties(test-gtx_color_space_YCoCg PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_color_space_YCoCg "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_color_space_YCoCg.exe")
  set_tests_properties(test-gtx_color_space_YCoCg PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_color_space_YCoCg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_color_space "D:/dev/glm/test/gtx/Debug/test-gtx_color_space.exe")
  set_tests_properties(test-gtx_color_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_color_space "D:/dev/glm/test/gtx/Release/test-gtx_color_space.exe")
  set_tests_properties(test-gtx_color_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_color_space "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_color_space.exe")
  set_tests_properties(test-gtx_color_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_color_space "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_color_space.exe")
  set_tests_properties(test-gtx_color_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_color_space NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_compatibility "D:/dev/glm/test/gtx/Debug/test-gtx_compatibility.exe")
  set_tests_properties(test-gtx_compatibility PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_compatibility "D:/dev/glm/test/gtx/Release/test-gtx_compatibility.exe")
  set_tests_properties(test-gtx_compatibility PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_compatibility "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_compatibility.exe")
  set_tests_properties(test-gtx_compatibility PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_compatibility "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_compatibility.exe")
  set_tests_properties(test-gtx_compatibility PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_compatibility NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_component_wise "D:/dev/glm/test/gtx/Debug/test-gtx_component_wise.exe")
  set_tests_properties(test-gtx_component_wise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_component_wise "D:/dev/glm/test/gtx/Release/test-gtx_component_wise.exe")
  set_tests_properties(test-gtx_component_wise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_component_wise "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_component_wise.exe")
  set_tests_properties(test-gtx_component_wise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_component_wise "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_component_wise.exe")
  set_tests_properties(test-gtx_component_wise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_component_wise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_euler_angle "D:/dev/glm/test/gtx/Debug/test-gtx_euler_angle.exe")
  set_tests_properties(test-gtx_euler_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_euler_angle "D:/dev/glm/test/gtx/Release/test-gtx_euler_angle.exe")
  set_tests_properties(test-gtx_euler_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_euler_angle "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_euler_angle.exe")
  set_tests_properties(test-gtx_euler_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_euler_angle "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_euler_angle.exe")
  set_tests_properties(test-gtx_euler_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_euler_angle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_extend "D:/dev/glm/test/gtx/Debug/test-gtx_extend.exe")
  set_tests_properties(test-gtx_extend PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_extend "D:/dev/glm/test/gtx/Release/test-gtx_extend.exe")
  set_tests_properties(test-gtx_extend PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_extend "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_extend.exe")
  set_tests_properties(test-gtx_extend PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_extend "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_extend.exe")
  set_tests_properties(test-gtx_extend PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_extend NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_extented_min_max "D:/dev/glm/test/gtx/Debug/test-gtx_extented_min_max.exe")
  set_tests_properties(test-gtx_extented_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_extented_min_max "D:/dev/glm/test/gtx/Release/test-gtx_extented_min_max.exe")
  set_tests_properties(test-gtx_extented_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_extented_min_max "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_extented_min_max.exe")
  set_tests_properties(test-gtx_extented_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_extented_min_max "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_extented_min_max.exe")
  set_tests_properties(test-gtx_extented_min_max PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_extented_min_max NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_fast_exponential "D:/dev/glm/test/gtx/Debug/test-gtx_fast_exponential.exe")
  set_tests_properties(test-gtx_fast_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_fast_exponential "D:/dev/glm/test/gtx/Release/test-gtx_fast_exponential.exe")
  set_tests_properties(test-gtx_fast_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_fast_exponential "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_fast_exponential.exe")
  set_tests_properties(test-gtx_fast_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_fast_exponential "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_fast_exponential.exe")
  set_tests_properties(test-gtx_fast_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_fast_exponential NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_fast_square_root "D:/dev/glm/test/gtx/Debug/test-gtx_fast_square_root.exe")
  set_tests_properties(test-gtx_fast_square_root PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_fast_square_root "D:/dev/glm/test/gtx/Release/test-gtx_fast_square_root.exe")
  set_tests_properties(test-gtx_fast_square_root PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_fast_square_root "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_fast_square_root.exe")
  set_tests_properties(test-gtx_fast_square_root PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_fast_square_root "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_fast_square_root.exe")
  set_tests_properties(test-gtx_fast_square_root PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_fast_square_root NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_fast_trigonometry "D:/dev/glm/test/gtx/Debug/test-gtx_fast_trigonometry.exe")
  set_tests_properties(test-gtx_fast_trigonometry PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_fast_trigonometry "D:/dev/glm/test/gtx/Release/test-gtx_fast_trigonometry.exe")
  set_tests_properties(test-gtx_fast_trigonometry PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_fast_trigonometry "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_fast_trigonometry.exe")
  set_tests_properties(test-gtx_fast_trigonometry PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_fast_trigonometry "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_fast_trigonometry.exe")
  set_tests_properties(test-gtx_fast_trigonometry PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_fast_trigonometry NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_gradient_paint "D:/dev/glm/test/gtx/Debug/test-gtx_gradient_paint.exe")
  set_tests_properties(test-gtx_gradient_paint PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_gradient_paint "D:/dev/glm/test/gtx/Release/test-gtx_gradient_paint.exe")
  set_tests_properties(test-gtx_gradient_paint PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_gradient_paint "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_gradient_paint.exe")
  set_tests_properties(test-gtx_gradient_paint PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_gradient_paint "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_gradient_paint.exe")
  set_tests_properties(test-gtx_gradient_paint PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_gradient_paint NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_handed_coordinate_space "D:/dev/glm/test/gtx/Debug/test-gtx_handed_coordinate_space.exe")
  set_tests_properties(test-gtx_handed_coordinate_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_handed_coordinate_space "D:/dev/glm/test/gtx/Release/test-gtx_handed_coordinate_space.exe")
  set_tests_properties(test-gtx_handed_coordinate_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_handed_coordinate_space "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_handed_coordinate_space.exe")
  set_tests_properties(test-gtx_handed_coordinate_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_handed_coordinate_space "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_handed_coordinate_space.exe")
  set_tests_properties(test-gtx_handed_coordinate_space PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_handed_coordinate_space NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_inertia "D:/dev/glm/test/gtx/Debug/test-gtx_inertia.exe")
  set_tests_properties(test-gtx_inertia PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_inertia "D:/dev/glm/test/gtx/Release/test-gtx_inertia.exe")
  set_tests_properties(test-gtx_inertia PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_inertia "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_inertia.exe")
  set_tests_properties(test-gtx_inertia PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_inertia "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_inertia.exe")
  set_tests_properties(test-gtx_inertia PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_inertia NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_integer "D:/dev/glm/test/gtx/Debug/test-gtx_integer.exe")
  set_tests_properties(test-gtx_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_integer "D:/dev/glm/test/gtx/Release/test-gtx_integer.exe")
  set_tests_properties(test-gtx_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_integer "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_integer.exe")
  set_tests_properties(test-gtx_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_integer "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_integer.exe")
  set_tests_properties(test-gtx_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_intersect "D:/dev/glm/test/gtx/Debug/test-gtx_intersect.exe")
  set_tests_properties(test-gtx_intersect PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_intersect "D:/dev/glm/test/gtx/Release/test-gtx_intersect.exe")
  set_tests_properties(test-gtx_intersect PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_intersect "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_intersect.exe")
  set_tests_properties(test-gtx_intersect PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_intersect "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_intersect.exe")
  set_tests_properties(test-gtx_intersect PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_intersect NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_io "D:/dev/glm/test/gtx/Debug/test-gtx_io.exe")
  set_tests_properties(test-gtx_io PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_io "D:/dev/glm/test/gtx/Release/test-gtx_io.exe")
  set_tests_properties(test-gtx_io PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_io "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_io.exe")
  set_tests_properties(test-gtx_io PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_io "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_io.exe")
  set_tests_properties(test-gtx_io PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_log_base "D:/dev/glm/test/gtx/Debug/test-gtx_log_base.exe")
  set_tests_properties(test-gtx_log_base PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_log_base "D:/dev/glm/test/gtx/Release/test-gtx_log_base.exe")
  set_tests_properties(test-gtx_log_base PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_log_base "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_log_base.exe")
  set_tests_properties(test-gtx_log_base PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_log_base "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_log_base.exe")
  set_tests_properties(test-gtx_log_base PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_log_base NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_cross_product "D:/dev/glm/test/gtx/Debug/test-gtx_matrix_cross_product.exe")
  set_tests_properties(test-gtx_matrix_cross_product PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_cross_product "D:/dev/glm/test/gtx/Release/test-gtx_matrix_cross_product.exe")
  set_tests_properties(test-gtx_matrix_cross_product PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_cross_product "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_matrix_cross_product.exe")
  set_tests_properties(test-gtx_matrix_cross_product PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_cross_product "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_cross_product.exe")
  set_tests_properties(test-gtx_matrix_cross_product PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_matrix_cross_product NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_interpolation "D:/dev/glm/test/gtx/Debug/test-gtx_matrix_interpolation.exe")
  set_tests_properties(test-gtx_matrix_interpolation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_interpolation "D:/dev/glm/test/gtx/Release/test-gtx_matrix_interpolation.exe")
  set_tests_properties(test-gtx_matrix_interpolation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_interpolation "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_matrix_interpolation.exe")
  set_tests_properties(test-gtx_matrix_interpolation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_interpolation "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_interpolation.exe")
  set_tests_properties(test-gtx_matrix_interpolation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_matrix_interpolation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_major_storage "D:/dev/glm/test/gtx/Debug/test-gtx_matrix_major_storage.exe")
  set_tests_properties(test-gtx_matrix_major_storage PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_major_storage "D:/dev/glm/test/gtx/Release/test-gtx_matrix_major_storage.exe")
  set_tests_properties(test-gtx_matrix_major_storage PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_major_storage "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_matrix_major_storage.exe")
  set_tests_properties(test-gtx_matrix_major_storage PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_major_storage "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_major_storage.exe")
  set_tests_properties(test-gtx_matrix_major_storage PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_matrix_major_storage NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_operation "D:/dev/glm/test/gtx/Debug/test-gtx_matrix_operation.exe")
  set_tests_properties(test-gtx_matrix_operation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_operation "D:/dev/glm/test/gtx/Release/test-gtx_matrix_operation.exe")
  set_tests_properties(test-gtx_matrix_operation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_operation "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_matrix_operation.exe")
  set_tests_properties(test-gtx_matrix_operation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_operation "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_operation.exe")
  set_tests_properties(test-gtx_matrix_operation PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_matrix_operation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_query "D:/dev/glm/test/gtx/Debug/test-gtx_matrix_query.exe")
  set_tests_properties(test-gtx_matrix_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_query "D:/dev/glm/test/gtx/Release/test-gtx_matrix_query.exe")
  set_tests_properties(test-gtx_matrix_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_query "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_matrix_query.exe")
  set_tests_properties(test-gtx_matrix_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_query "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_query.exe")
  set_tests_properties(test-gtx_matrix_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_matrix_query NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_matrix_transform_2d "D:/dev/glm/test/gtx/Debug/test-gtx_matrix_transform_2d.exe")
  set_tests_properties(test-gtx_matrix_transform_2d PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_matrix_transform_2d "D:/dev/glm/test/gtx/Release/test-gtx_matrix_transform_2d.exe")
  set_tests_properties(test-gtx_matrix_transform_2d PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_matrix_transform_2d "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_matrix_transform_2d.exe")
  set_tests_properties(test-gtx_matrix_transform_2d PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_matrix_transform_2d "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_matrix_transform_2d.exe")
  set_tests_properties(test-gtx_matrix_transform_2d PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_matrix_transform_2d NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_multiple "D:/dev/glm/test/gtx/Debug/test-gtx_multiple.exe")
  set_tests_properties(test-gtx_multiple PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_multiple "D:/dev/glm/test/gtx/Release/test-gtx_multiple.exe")
  set_tests_properties(test-gtx_multiple PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_multiple "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_multiple.exe")
  set_tests_properties(test-gtx_multiple PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_multiple "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_multiple.exe")
  set_tests_properties(test-gtx_multiple PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_multiple NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_norm "D:/dev/glm/test/gtx/Debug/test-gtx_norm.exe")
  set_tests_properties(test-gtx_norm PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_norm "D:/dev/glm/test/gtx/Release/test-gtx_norm.exe")
  set_tests_properties(test-gtx_norm PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_norm "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_norm.exe")
  set_tests_properties(test-gtx_norm PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_norm "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_norm.exe")
  set_tests_properties(test-gtx_norm PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_norm NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_normal "D:/dev/glm/test/gtx/Debug/test-gtx_normal.exe")
  set_tests_properties(test-gtx_normal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_normal "D:/dev/glm/test/gtx/Release/test-gtx_normal.exe")
  set_tests_properties(test-gtx_normal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_normal "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_normal.exe")
  set_tests_properties(test-gtx_normal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_normal "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_normal.exe")
  set_tests_properties(test-gtx_normal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_normal NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_normalize_dot "D:/dev/glm/test/gtx/Debug/test-gtx_normalize_dot.exe")
  set_tests_properties(test-gtx_normalize_dot PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;30;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_normalize_dot "D:/dev/glm/test/gtx/Release/test-gtx_normalize_dot.exe")
  set_tests_properties(test-gtx_normalize_dot PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;30;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_normalize_dot "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_normalize_dot.exe")
  set_tests_properties(test-gtx_normalize_dot PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;30;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_normalize_dot "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_normalize_dot.exe")
  set_tests_properties(test-gtx_normalize_dot PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;30;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_normalize_dot NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_number_precision "D:/dev/glm/test/gtx/Debug/test-gtx_number_precision.exe")
  set_tests_properties(test-gtx_number_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;31;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_number_precision "D:/dev/glm/test/gtx/Release/test-gtx_number_precision.exe")
  set_tests_properties(test-gtx_number_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;31;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_number_precision "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_number_precision.exe")
  set_tests_properties(test-gtx_number_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;31;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_number_precision "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_number_precision.exe")
  set_tests_properties(test-gtx_number_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;31;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_number_precision NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_orthonormalize "D:/dev/glm/test/gtx/Debug/test-gtx_orthonormalize.exe")
  set_tests_properties(test-gtx_orthonormalize PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;32;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_orthonormalize "D:/dev/glm/test/gtx/Release/test-gtx_orthonormalize.exe")
  set_tests_properties(test-gtx_orthonormalize PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;32;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_orthonormalize "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_orthonormalize.exe")
  set_tests_properties(test-gtx_orthonormalize PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;32;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_orthonormalize "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_orthonormalize.exe")
  set_tests_properties(test-gtx_orthonormalize PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;32;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_orthonormalize NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_optimum_pow "D:/dev/glm/test/gtx/Debug/test-gtx_optimum_pow.exe")
  set_tests_properties(test-gtx_optimum_pow PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;33;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_optimum_pow "D:/dev/glm/test/gtx/Release/test-gtx_optimum_pow.exe")
  set_tests_properties(test-gtx_optimum_pow PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;33;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_optimum_pow "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_optimum_pow.exe")
  set_tests_properties(test-gtx_optimum_pow PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;33;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_optimum_pow "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_optimum_pow.exe")
  set_tests_properties(test-gtx_optimum_pow PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;33;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_optimum_pow NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_perpendicular "D:/dev/glm/test/gtx/Debug/test-gtx_perpendicular.exe")
  set_tests_properties(test-gtx_perpendicular PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;34;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_perpendicular "D:/dev/glm/test/gtx/Release/test-gtx_perpendicular.exe")
  set_tests_properties(test-gtx_perpendicular PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;34;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_perpendicular "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_perpendicular.exe")
  set_tests_properties(test-gtx_perpendicular PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;34;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_perpendicular "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_perpendicular.exe")
  set_tests_properties(test-gtx_perpendicular PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;34;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_perpendicular NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_polar_coordinates "D:/dev/glm/test/gtx/Debug/test-gtx_polar_coordinates.exe")
  set_tests_properties(test-gtx_polar_coordinates PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;35;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_polar_coordinates "D:/dev/glm/test/gtx/Release/test-gtx_polar_coordinates.exe")
  set_tests_properties(test-gtx_polar_coordinates PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;35;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_polar_coordinates "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_polar_coordinates.exe")
  set_tests_properties(test-gtx_polar_coordinates PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;35;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_polar_coordinates "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_polar_coordinates.exe")
  set_tests_properties(test-gtx_polar_coordinates PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;35;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_polar_coordinates NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_projection "D:/dev/glm/test/gtx/Debug/test-gtx_projection.exe")
  set_tests_properties(test-gtx_projection PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;36;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_projection "D:/dev/glm/test/gtx/Release/test-gtx_projection.exe")
  set_tests_properties(test-gtx_projection PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;36;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_projection "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_projection.exe")
  set_tests_properties(test-gtx_projection PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;36;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_projection "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_projection.exe")
  set_tests_properties(test-gtx_projection PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;36;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_projection NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_quaternion "D:/dev/glm/test/gtx/Debug/test-gtx_quaternion.exe")
  set_tests_properties(test-gtx_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;37;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_quaternion "D:/dev/glm/test/gtx/Release/test-gtx_quaternion.exe")
  set_tests_properties(test-gtx_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;37;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_quaternion "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_quaternion.exe")
  set_tests_properties(test-gtx_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;37;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_quaternion "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_quaternion.exe")
  set_tests_properties(test-gtx_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;37;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_quaternion NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_dual_quaternion "D:/dev/glm/test/gtx/Debug/test-gtx_dual_quaternion.exe")
  set_tests_properties(test-gtx_dual_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;38;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_dual_quaternion "D:/dev/glm/test/gtx/Release/test-gtx_dual_quaternion.exe")
  set_tests_properties(test-gtx_dual_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;38;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_dual_quaternion "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_dual_quaternion.exe")
  set_tests_properties(test-gtx_dual_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;38;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_dual_quaternion "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_dual_quaternion.exe")
  set_tests_properties(test-gtx_dual_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;38;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_dual_quaternion NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_rotate_normalized_axis "D:/dev/glm/test/gtx/Debug/test-gtx_rotate_normalized_axis.exe")
  set_tests_properties(test-gtx_rotate_normalized_axis PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;39;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_rotate_normalized_axis "D:/dev/glm/test/gtx/Release/test-gtx_rotate_normalized_axis.exe")
  set_tests_properties(test-gtx_rotate_normalized_axis PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;39;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_rotate_normalized_axis "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_rotate_normalized_axis.exe")
  set_tests_properties(test-gtx_rotate_normalized_axis PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;39;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_rotate_normalized_axis "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_rotate_normalized_axis.exe")
  set_tests_properties(test-gtx_rotate_normalized_axis PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;39;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_rotate_normalized_axis NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_rotate_vector "D:/dev/glm/test/gtx/Debug/test-gtx_rotate_vector.exe")
  set_tests_properties(test-gtx_rotate_vector PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;40;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_rotate_vector "D:/dev/glm/test/gtx/Release/test-gtx_rotate_vector.exe")
  set_tests_properties(test-gtx_rotate_vector PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;40;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_rotate_vector "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_rotate_vector.exe")
  set_tests_properties(test-gtx_rotate_vector PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;40;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_rotate_vector "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_rotate_vector.exe")
  set_tests_properties(test-gtx_rotate_vector PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;40;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_rotate_vector NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_scalar_relational "D:/dev/glm/test/gtx/Debug/test-gtx_scalar_relational.exe")
  set_tests_properties(test-gtx_scalar_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;41;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_scalar_relational "D:/dev/glm/test/gtx/Release/test-gtx_scalar_relational.exe")
  set_tests_properties(test-gtx_scalar_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;41;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_scalar_relational "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_scalar_relational.exe")
  set_tests_properties(test-gtx_scalar_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;41;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_scalar_relational "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_scalar_relational.exe")
  set_tests_properties(test-gtx_scalar_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;41;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_scalar_relational NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_simd_vec4 "D:/dev/glm/test/gtx/Debug/test-gtx_simd_vec4.exe")
  set_tests_properties(test-gtx_simd_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;42;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_simd_vec4 "D:/dev/glm/test/gtx/Release/test-gtx_simd_vec4.exe")
  set_tests_properties(test-gtx_simd_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;42;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_simd_vec4 "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_simd_vec4.exe")
  set_tests_properties(test-gtx_simd_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;42;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_simd_vec4 "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_simd_vec4.exe")
  set_tests_properties(test-gtx_simd_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;42;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_simd_vec4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_simd_mat4 "D:/dev/glm/test/gtx/Debug/test-gtx_simd_mat4.exe")
  set_tests_properties(test-gtx_simd_mat4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;43;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_simd_mat4 "D:/dev/glm/test/gtx/Release/test-gtx_simd_mat4.exe")
  set_tests_properties(test-gtx_simd_mat4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;43;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_simd_mat4 "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_simd_mat4.exe")
  set_tests_properties(test-gtx_simd_mat4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;43;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_simd_mat4 "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_simd_mat4.exe")
  set_tests_properties(test-gtx_simd_mat4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;43;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_simd_mat4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_spline "D:/dev/glm/test/gtx/Debug/test-gtx_spline.exe")
  set_tests_properties(test-gtx_spline PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;44;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_spline "D:/dev/glm/test/gtx/Release/test-gtx_spline.exe")
  set_tests_properties(test-gtx_spline PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;44;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_spline "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_spline.exe")
  set_tests_properties(test-gtx_spline PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;44;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_spline "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_spline.exe")
  set_tests_properties(test-gtx_spline PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;44;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_spline NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_string_cast "D:/dev/glm/test/gtx/Debug/test-gtx_string_cast.exe")
  set_tests_properties(test-gtx_string_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;45;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_string_cast "D:/dev/glm/test/gtx/Release/test-gtx_string_cast.exe")
  set_tests_properties(test-gtx_string_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;45;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_string_cast "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_string_cast.exe")
  set_tests_properties(test-gtx_string_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;45;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_string_cast "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_string_cast.exe")
  set_tests_properties(test-gtx_string_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;45;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_string_cast NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_vector_angle "D:/dev/glm/test/gtx/Debug/test-gtx_vector_angle.exe")
  set_tests_properties(test-gtx_vector_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;46;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_vector_angle "D:/dev/glm/test/gtx/Release/test-gtx_vector_angle.exe")
  set_tests_properties(test-gtx_vector_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;46;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_vector_angle "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_vector_angle.exe")
  set_tests_properties(test-gtx_vector_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;46;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_vector_angle "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_vector_angle.exe")
  set_tests_properties(test-gtx_vector_angle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;46;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_vector_angle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtx_vector_query "D:/dev/glm/test/gtx/Debug/test-gtx_vector_query.exe")
  set_tests_properties(test-gtx_vector_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;47;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtx_vector_query "D:/dev/glm/test/gtx/Release/test-gtx_vector_query.exe")
  set_tests_properties(test-gtx_vector_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;47;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtx_vector_query "D:/dev/glm/test/gtx/MinSizeRel/test-gtx_vector_query.exe")
  set_tests_properties(test-gtx_vector_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;47;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtx_vector_query "D:/dev/glm/test/gtx/RelWithDebInfo/test-gtx_vector_query.exe")
  set_tests_properties(test-gtx_vector_query PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;47;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtx/CMakeLists.txt;0;")
else()
  add_test(test-gtx_vector_query NOT_AVAILABLE)
endif()
