# CMake generated Testfile for 
# Source directory: R:/OpenGL Resources/glm-0.9.5.4/glm/test/core
# Build directory: D:/dev/glm/test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_cast "D:/dev/glm/test/core/Debug/test-core_type_cast.exe")
  set_tests_properties(test-core_type_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_cast "D:/dev/glm/test/core/Release/test-core_type_cast.exe")
  set_tests_properties(test-core_type_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_cast "D:/dev/glm/test/core/MinSizeRel/test-core_type_cast.exe")
  set_tests_properties(test-core_type_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_cast "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_cast.exe")
  set_tests_properties(test-core_type_cast PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_cast NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_float "D:/dev/glm/test/core/Debug/test-core_type_float.exe")
  set_tests_properties(test-core_type_float PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_float "D:/dev/glm/test/core/Release/test-core_type_float.exe")
  set_tests_properties(test-core_type_float PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_float "D:/dev/glm/test/core/MinSizeRel/test-core_type_float.exe")
  set_tests_properties(test-core_type_float PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_float "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_float.exe")
  set_tests_properties(test-core_type_float PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_float NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_int "D:/dev/glm/test/core/Debug/test-core_type_int.exe")
  set_tests_properties(test-core_type_int PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_int "D:/dev/glm/test/core/Release/test-core_type_int.exe")
  set_tests_properties(test-core_type_int PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_int "D:/dev/glm/test/core/MinSizeRel/test-core_type_int.exe")
  set_tests_properties(test-core_type_int PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_int "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_int.exe")
  set_tests_properties(test-core_type_int PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_int NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_length "D:/dev/glm/test/core/Debug/test-core_type_length.exe")
  set_tests_properties(test-core_type_length PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_length "D:/dev/glm/test/core/Release/test-core_type_length.exe")
  set_tests_properties(test-core_type_length PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_length "D:/dev/glm/test/core/MinSizeRel/test-core_type_length.exe")
  set_tests_properties(test-core_type_length PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_length "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_length.exe")
  set_tests_properties(test-core_type_length PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_length NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat2x2 "D:/dev/glm/test/core/Debug/test-core_type_mat2x2.exe")
  set_tests_properties(test-core_type_mat2x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat2x2 "D:/dev/glm/test/core/Release/test-core_type_mat2x2.exe")
  set_tests_properties(test-core_type_mat2x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat2x2 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat2x2.exe")
  set_tests_properties(test-core_type_mat2x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat2x2 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat2x2.exe")
  set_tests_properties(test-core_type_mat2x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat2x2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat2x3 "D:/dev/glm/test/core/Debug/test-core_type_mat2x3.exe")
  set_tests_properties(test-core_type_mat2x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat2x3 "D:/dev/glm/test/core/Release/test-core_type_mat2x3.exe")
  set_tests_properties(test-core_type_mat2x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat2x3 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat2x3.exe")
  set_tests_properties(test-core_type_mat2x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat2x3 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat2x3.exe")
  set_tests_properties(test-core_type_mat2x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat2x3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat2x4 "D:/dev/glm/test/core/Debug/test-core_type_mat2x4.exe")
  set_tests_properties(test-core_type_mat2x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat2x4 "D:/dev/glm/test/core/Release/test-core_type_mat2x4.exe")
  set_tests_properties(test-core_type_mat2x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat2x4 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat2x4.exe")
  set_tests_properties(test-core_type_mat2x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat2x4 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat2x4.exe")
  set_tests_properties(test-core_type_mat2x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat2x4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat3x2 "D:/dev/glm/test/core/Debug/test-core_type_mat3x2.exe")
  set_tests_properties(test-core_type_mat3x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat3x2 "D:/dev/glm/test/core/Release/test-core_type_mat3x2.exe")
  set_tests_properties(test-core_type_mat3x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat3x2 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat3x2.exe")
  set_tests_properties(test-core_type_mat3x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat3x2 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat3x2.exe")
  set_tests_properties(test-core_type_mat3x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat3x2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat3x3 "D:/dev/glm/test/core/Debug/test-core_type_mat3x3.exe")
  set_tests_properties(test-core_type_mat3x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat3x3 "D:/dev/glm/test/core/Release/test-core_type_mat3x3.exe")
  set_tests_properties(test-core_type_mat3x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat3x3 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat3x3.exe")
  set_tests_properties(test-core_type_mat3x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat3x3 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat3x3.exe")
  set_tests_properties(test-core_type_mat3x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat3x3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat3x4 "D:/dev/glm/test/core/Debug/test-core_type_mat3x4.exe")
  set_tests_properties(test-core_type_mat3x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat3x4 "D:/dev/glm/test/core/Release/test-core_type_mat3x4.exe")
  set_tests_properties(test-core_type_mat3x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat3x4 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat3x4.exe")
  set_tests_properties(test-core_type_mat3x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat3x4 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat3x4.exe")
  set_tests_properties(test-core_type_mat3x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat3x4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat4x2 "D:/dev/glm/test/core/Debug/test-core_type_mat4x2.exe")
  set_tests_properties(test-core_type_mat4x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat4x2 "D:/dev/glm/test/core/Release/test-core_type_mat4x2.exe")
  set_tests_properties(test-core_type_mat4x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat4x2 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat4x2.exe")
  set_tests_properties(test-core_type_mat4x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat4x2 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat4x2.exe")
  set_tests_properties(test-core_type_mat4x2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat4x2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat4x3 "D:/dev/glm/test/core/Debug/test-core_type_mat4x3.exe")
  set_tests_properties(test-core_type_mat4x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat4x3 "D:/dev/glm/test/core/Release/test-core_type_mat4x3.exe")
  set_tests_properties(test-core_type_mat4x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat4x3 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat4x3.exe")
  set_tests_properties(test-core_type_mat4x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat4x3 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat4x3.exe")
  set_tests_properties(test-core_type_mat4x3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat4x3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_mat4x4 "D:/dev/glm/test/core/Debug/test-core_type_mat4x4.exe")
  set_tests_properties(test-core_type_mat4x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_mat4x4 "D:/dev/glm/test/core/Release/test-core_type_mat4x4.exe")
  set_tests_properties(test-core_type_mat4x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_mat4x4 "D:/dev/glm/test/core/MinSizeRel/test-core_type_mat4x4.exe")
  set_tests_properties(test-core_type_mat4x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_mat4x4 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_mat4x4.exe")
  set_tests_properties(test-core_type_mat4x4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_mat4x4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec1 "D:/dev/glm/test/core/Debug/test-core_type_vec1.exe")
  set_tests_properties(test-core_type_vec1 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec1 "D:/dev/glm/test/core/Release/test-core_type_vec1.exe")
  set_tests_properties(test-core_type_vec1 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec1 "D:/dev/glm/test/core/MinSizeRel/test-core_type_vec1.exe")
  set_tests_properties(test-core_type_vec1 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec1 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_vec1.exe")
  set_tests_properties(test-core_type_vec1 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_vec1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec2 "D:/dev/glm/test/core/Debug/test-core_type_vec2.exe")
  set_tests_properties(test-core_type_vec2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec2 "D:/dev/glm/test/core/Release/test-core_type_vec2.exe")
  set_tests_properties(test-core_type_vec2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec2 "D:/dev/glm/test/core/MinSizeRel/test-core_type_vec2.exe")
  set_tests_properties(test-core_type_vec2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec2 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_vec2.exe")
  set_tests_properties(test-core_type_vec2 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;15;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_vec2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec3 "D:/dev/glm/test/core/Debug/test-core_type_vec3.exe")
  set_tests_properties(test-core_type_vec3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec3 "D:/dev/glm/test/core/Release/test-core_type_vec3.exe")
  set_tests_properties(test-core_type_vec3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec3 "D:/dev/glm/test/core/MinSizeRel/test-core_type_vec3.exe")
  set_tests_properties(test-core_type_vec3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec3 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_vec3.exe")
  set_tests_properties(test-core_type_vec3 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;16;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_vec3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_type_vec4 "D:/dev/glm/test/core/Debug/test-core_type_vec4.exe")
  set_tests_properties(test-core_type_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_type_vec4 "D:/dev/glm/test/core/Release/test-core_type_vec4.exe")
  set_tests_properties(test-core_type_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_type_vec4 "D:/dev/glm/test/core/MinSizeRel/test-core_type_vec4.exe")
  set_tests_properties(test-core_type_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_type_vec4 "D:/dev/glm/test/core/RelWithDebInfo/test-core_type_vec4.exe")
  set_tests_properties(test-core_type_vec4 PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;17;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_type_vec4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_common "D:/dev/glm/test/core/Debug/test-core_func_common.exe")
  set_tests_properties(test-core_func_common PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_common "D:/dev/glm/test/core/Release/test-core_func_common.exe")
  set_tests_properties(test-core_func_common PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_common "D:/dev/glm/test/core/MinSizeRel/test-core_func_common.exe")
  set_tests_properties(test-core_func_common PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_common "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_common.exe")
  set_tests_properties(test-core_func_common PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;18;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_common NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_exponential "D:/dev/glm/test/core/Debug/test-core_func_exponential.exe")
  set_tests_properties(test-core_func_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_exponential "D:/dev/glm/test/core/Release/test-core_func_exponential.exe")
  set_tests_properties(test-core_func_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_exponential "D:/dev/glm/test/core/MinSizeRel/test-core_func_exponential.exe")
  set_tests_properties(test-core_func_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_exponential "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_exponential.exe")
  set_tests_properties(test-core_func_exponential PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;19;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_exponential NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_geometric "D:/dev/glm/test/core/Debug/test-core_func_geometric.exe")
  set_tests_properties(test-core_func_geometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_geometric "D:/dev/glm/test/core/Release/test-core_func_geometric.exe")
  set_tests_properties(test-core_func_geometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_geometric "D:/dev/glm/test/core/MinSizeRel/test-core_func_geometric.exe")
  set_tests_properties(test-core_func_geometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_geometric "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_geometric.exe")
  set_tests_properties(test-core_func_geometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;20;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_geometric NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_integer "D:/dev/glm/test/core/Debug/test-core_func_integer.exe")
  set_tests_properties(test-core_func_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_integer "D:/dev/glm/test/core/Release/test-core_func_integer.exe")
  set_tests_properties(test-core_func_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_integer "D:/dev/glm/test/core/MinSizeRel/test-core_func_integer.exe")
  set_tests_properties(test-core_func_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_integer "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_integer.exe")
  set_tests_properties(test-core_func_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;21;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_matrix "D:/dev/glm/test/core/Debug/test-core_func_matrix.exe")
  set_tests_properties(test-core_func_matrix PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_matrix "D:/dev/glm/test/core/Release/test-core_func_matrix.exe")
  set_tests_properties(test-core_func_matrix PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_matrix "D:/dev/glm/test/core/MinSizeRel/test-core_func_matrix.exe")
  set_tests_properties(test-core_func_matrix PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_matrix "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_matrix.exe")
  set_tests_properties(test-core_func_matrix PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;22;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_matrix NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_noise "D:/dev/glm/test/core/Debug/test-core_func_noise.exe")
  set_tests_properties(test-core_func_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_noise "D:/dev/glm/test/core/Release/test-core_func_noise.exe")
  set_tests_properties(test-core_func_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_noise "D:/dev/glm/test/core/MinSizeRel/test-core_func_noise.exe")
  set_tests_properties(test-core_func_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_noise "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_noise.exe")
  set_tests_properties(test-core_func_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;23;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_noise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_packing "D:/dev/glm/test/core/Debug/test-core_func_packing.exe")
  set_tests_properties(test-core_func_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_packing "D:/dev/glm/test/core/Release/test-core_func_packing.exe")
  set_tests_properties(test-core_func_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_packing "D:/dev/glm/test/core/MinSizeRel/test-core_func_packing.exe")
  set_tests_properties(test-core_func_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_packing "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_packing.exe")
  set_tests_properties(test-core_func_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;24;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_packing NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_trigonometric "D:/dev/glm/test/core/Debug/test-core_func_trigonometric.exe")
  set_tests_properties(test-core_func_trigonometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_trigonometric "D:/dev/glm/test/core/Release/test-core_func_trigonometric.exe")
  set_tests_properties(test-core_func_trigonometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_trigonometric "D:/dev/glm/test/core/MinSizeRel/test-core_func_trigonometric.exe")
  set_tests_properties(test-core_func_trigonometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_trigonometric "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_trigonometric.exe")
  set_tests_properties(test-core_func_trigonometric PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;25;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_trigonometric NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_vector_relational "D:/dev/glm/test/core/Debug/test-core_func_vector_relational.exe")
  set_tests_properties(test-core_func_vector_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_vector_relational "D:/dev/glm/test/core/Release/test-core_func_vector_relational.exe")
  set_tests_properties(test-core_func_vector_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_vector_relational "D:/dev/glm/test/core/MinSizeRel/test-core_func_vector_relational.exe")
  set_tests_properties(test-core_func_vector_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_vector_relational "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_vector_relational.exe")
  set_tests_properties(test-core_func_vector_relational PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;26;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_vector_relational NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_func_swizzle "D:/dev/glm/test/core/Debug/test-core_func_swizzle.exe")
  set_tests_properties(test-core_func_swizzle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_func_swizzle "D:/dev/glm/test/core/Release/test-core_func_swizzle.exe")
  set_tests_properties(test-core_func_swizzle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_func_swizzle "D:/dev/glm/test/core/MinSizeRel/test-core_func_swizzle.exe")
  set_tests_properties(test-core_func_swizzle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_func_swizzle "D:/dev/glm/test/core/RelWithDebInfo/test-core_func_swizzle.exe")
  set_tests_properties(test-core_func_swizzle PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;27;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_func_swizzle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_setup_message "D:/dev/glm/test/core/Debug/test-core_setup_message.exe")
  set_tests_properties(test-core_setup_message PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_setup_message "D:/dev/glm/test/core/Release/test-core_setup_message.exe")
  set_tests_properties(test-core_setup_message PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_setup_message "D:/dev/glm/test/core/MinSizeRel/test-core_setup_message.exe")
  set_tests_properties(test-core_setup_message PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_setup_message "D:/dev/glm/test/core/RelWithDebInfo/test-core_setup_message.exe")
  set_tests_properties(test-core_setup_message PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;28;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_setup_message NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-core_setup_precision "D:/dev/glm/test/core/Debug/test-core_setup_precision.exe")
  set_tests_properties(test-core_setup_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-core_setup_precision "D:/dev/glm/test/core/Release/test-core_setup_precision.exe")
  set_tests_properties(test-core_setup_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-core_setup_precision "D:/dev/glm/test/core/MinSizeRel/test-core_setup_precision.exe")
  set_tests_properties(test-core_setup_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-core_setup_precision "D:/dev/glm/test/core/RelWithDebInfo/test-core_setup_precision.exe")
  set_tests_properties(test-core_setup_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;29;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/core/CMakeLists.txt;0;")
else()
  add_test(test-core_setup_precision NOT_AVAILABLE)
endif()
