# CMake generated Testfile for 
# Source directory: R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc
# Build directory: D:/dev/glm/test/gtc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_constants "D:/dev/glm/test/gtc/Debug/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_constants "D:/dev/glm/test/gtc/Release/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_constants "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_constants "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_constants NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_epsilon "D:/dev/glm/test/gtc/Debug/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_epsilon "D:/dev/glm/test/gtc/Release/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_epsilon "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_epsilon "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_epsilon NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_access "D:/dev/glm/test/gtc/Debug/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_access "D:/dev/glm/test/gtc/Release/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_access "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_access "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_access NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_integer "D:/dev/glm/test/gtc/Debug/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_integer "D:/dev/glm/test/gtc/Release/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_integer "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_integer "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_integer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_inverse "D:/dev/glm/test/gtc/Debug/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_inverse "D:/dev/glm/test/gtc/Release/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_inverse "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_inverse "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_inverse NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_transform "D:/dev/glm/test/gtc/Debug/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_transform "D:/dev/glm/test/gtc/Release/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_transform "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_transform "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_transform NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_noise "D:/dev/glm/test/gtc/Debug/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_noise "D:/dev/glm/test/gtc/Release/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_noise "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_noise "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_noise NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_packing "D:/dev/glm/test/gtc/Debug/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_packing "D:/dev/glm/test/gtc/Release/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_packing "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_packing "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_packing NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_quaternion "D:/dev/glm/test/gtc/Debug/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_quaternion "D:/dev/glm/test/gtc/Release/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_quaternion "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_quaternion "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_quaternion NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_random "D:/dev/glm/test/gtc/Debug/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_random "D:/dev/glm/test/gtc/Release/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_random "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_random "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_random NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_reciprocal "D:/dev/glm/test/gtc/Debug/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_reciprocal "D:/dev/glm/test/gtc/Release/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_reciprocal "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_reciprocal "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_reciprocal NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_precision "D:/dev/glm/test/gtc/Debug/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_precision "D:/dev/glm/test/gtc/Release/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_precision "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_precision "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_type_precision NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_ptr "D:/dev/glm/test/gtc/Debug/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_ptr "D:/dev/glm/test/gtc/Release/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_ptr "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_ptr "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_type_ptr NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_ulp "D:/dev/glm/test/gtc/Debug/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_ulp "D:/dev/glm/test/gtc/Release/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_ulp "D:/dev/glm/test/gtc/MinSizeRel/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_ulp "D:/dev/glm/test/gtc/RelWithDebInfo/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "R:/OpenGL Resources/glm-0.9.5.4/glm/test/CMakeLists.txt;6;add_test;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;R:/OpenGL Resources/glm-0.9.5.4/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_ulp NOT_AVAILABLE)
endif()
